id: monarch_search
schema_generating: true
description: Monarch search
display_name: Monarch_search
document_category: monarch_search
weight: 1

## For search
boost_weights: label_searchable^1.0 definition_searchable^1.0 synonym_searchable^1.0 iri_searchable^1.0 id_searchable^1.0 id^2 iri^2 equivalent_iri^2 equivalent_curie^2 equivalent_iri_searchable^1.0 equivalent_curie_searchable^1.0 taxon_label_searchable^1.0 taxon_label_synonym_searchable^1.0

## Results table, horizontal
result_weights: id^1.0

## Ordering of facets, vertical
filter_weights: id^1.0

## SOLR FIELD DEFINITIONS

fields:

  - id: id
    description: "A unique identifier (CURIE if exists, or IRI as fallback)."
    display_name: id
    type: string
    property: []
    searchable: true

  - id: label
    description: "The labels."
    display_name: label
    type: string
    cardinality: multi
    property: []
    searchable: true

  - id: synonym
    description: "The synonyms."
    display_name: synonym
    type: string
    cardinality: multi
    property: []
    searchable: true
    
  - id: abbreviation
    description: "The abbreviations."
    display_name: abbreviation
    type: string
    cardinality: multi
    property: []
    searchable: true

  - id: definition
    description: "The definitions."
    display_name: definition
    type: string
    cardinality: multi
    property: []
    searchable: true

  - id: taxon
    description: "The taxon."
    display_name: taxon
    type: string
    cardinality: single
    property: []
    searchable: true

  - id: taxon_label
    description: "The taxon label."
    display_name: taxon
    type: string
    cardinality: single
    property: []
    searchable: true

  - id: taxon_label_synonym
    description: "The taxon synonym label."
    display_name: taxon
    type: string
    cardinality: multi
    property: []
    searchable: true

  - id: category
    description: "The categories."
    display_name: category
    type: string
    cardinality: multi
    property: []
    searchable: true

  - id: equivalent_curie
    description: "The equivalent CURIE."
    display_name: equivalentCurie
    type: string
    cardinality: multi
    property: []
    searchable: true

  - id: leaf
    description: "Is leaf node?"
    display_name: leaf
    type: boolean
    cardinality: single
    property: []
    searchable: false
  
  - id: has_phenotype
    description: "Connected to phenotypes"
    display_name: has_phenotype
    type: boolean
    cardinality: single
    property: []
    searchable: false
    
  - id: prefix
    description: "Curie prefix"
    display_name: prefix
    type: string
    cardinality: single
    property: []
    searchable: false

  - id: edges
    description: "Number of edges connected to entity"
    display_name: edges
    type: integer
    cardinality: single
    property: []
    searchable: false
